# Generated by Django 5.2 on 2025-06-25 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soil', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop_price_data',
            old_name='crop',
            new_name='Crop',
        ),
        migrations.RenameField(
            model_name='crop_price_data',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='crop_price_data',
            old_name='district',
            new_name='District',
        ),
        migrations.RenameField(
            model_name='crop_price_data',
            old_name='market',
            new_name='Market',
        ),
        migrations.RenameField(
            model_name='crop_price_data',
            old_name='price_inr_per_quintal',
            new_name='Price',
        ),
    ]
