# Generated by Django 5.2 on 2025-06-25 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soil', '0002_rename_crop_crop_price_data_crop_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop_price_data',
            old_name='Price',
            new_name='price_inr_per_quintal',
        ),
    ]
