# Generated by Django 5.2 on 2025-06-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soil', '0003_rename_price_crop_price_data_price_inr_per_quintal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop_price_data',
            name='price_inr_per_quintal',
            field=models.FloatField(),
        ),
    ]
