# Generated by Django 5.2 on 2025-06-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soil', '0004_alter_crop_price_data_price_inr_per_quintal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop_production_data',
            old_name='crop',
            new_name='Crop',
        ),
        migrations.RenameField(
            model_name='crop_production_data',
            old_name='district',
            new_name='District',
        ),
        migrations.RenameField(
            model_name='crop_production_data',
            old_name='season',
            new_name='Season',
        ),
        migrations.AlterField(
            model_name='crop_price_data',
            name='price_inr_per_quintal',
            field=models.FloatField(help_text='Price (INR/quintal)'),
        ),
    ]
