# Generated by Django 5.2 on 2025-06-25 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soil', '0005_rename_crop_crop_production_data_crop_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rajasthan_city_climate_split',
            old_name='avg_temp_c',
            new_name='Avg_temp_c',
        ),
        migrations.RenameField(
            model_name='rajasthan_city_climate_split',
            old_name='avg_temp_f',
            new_name='Avg_temp_f',
        ),
        migrations.RenameField(
            model_name='rajasthan_city_climate_split',
            old_name='city',
            new_name='City',
        ),
        migrations.RenameField(
            model_name='rajasthan_city_climate_split',
            old_name='climate_zone',
            new_name='Climate_zone',
        ),
        migrations.RenameField(
            model_name='rajasthan_city_climate_split',
            old_name='precipitation_in',
            new_name='Precipitation_in',
        ),
        migrations.RenameField(
            model_name='rajasthan_city_climate_split',
            old_name='precipitation_mm',
            new_name='Precipitation_mm',
        ),
    ]
