# Generated by Django 5.2 on 2025-06-25 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soil', '0006_rename_avg_temp_c_rajasthan_city_climate_split_avg_temp_c_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rajasthan_district_forest_stat',
            old_name='district',
            new_name='District',
        ),
    ]
