# Generated by Django 5.2 on 2025-06-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soil', '0007_rename_district_rajasthan_district_forest_stat_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockmaster',
            name='district',
            field=models.CharField(default='defaultCity', help_text='District where block is located', max_length=100),
        ),
        migrations.AddField(
            model_name='digitalelevationdata',
            name='district',
            field=models.CharField(default='defaultCity', help_text='District where project is present', max_length=100),
        ),
        migrations.AddField(
            model_name='grasslandwaterbodiesdata',
            name='district',
            field=models.CharField(default='defaultCity', help_text='District where project is present', max_length=100),
        ),
        migrations.AddField(
            model_name='groundwaterdepth',
            name='district',
            field=models.CharField(default='defaultCity', help_text='District where project is present', max_length=100),
        ),
        migrations.AddField(
            model_name='humansettlementdata',
            name='district',
            field=models.CharField(default='defaultCity', help_text='District where project is present', max_length=100),
        ),
        migrations.AddField(
            model_name='masterproduce',
            name='district',
            field=models.CharField(default='defaultCity', help_text='District where produce is located', max_length=100),
        ),
        migrations.AddField(
            model_name='nurserydata',
            name='district',
            field=models.CharField(default='defaultCity', help_text='District where nursery is located', max_length=100),
        ),
        migrations.AddField(
            model_name='offencedata',
            name='district',
            field=models.CharField(default='defaultCity', help_text='District where offence was reported', max_length=100),
        ),
        migrations.AddField(
            model_name='plantationsite',
            name='district',
            field=models.CharField(default='defaultCity', help_text='District where plantation site is present', max_length=100),
        ),
        migrations.AddField(
            model_name='produceauction',
            name='district',
            field=models.CharField(default='defaultCity', help_text='District where auction was conducted', max_length=100),
        ),
        migrations.AddField(
            model_name='projectmonthlyprogress',
            name='district',
            field=models.CharField(default='defaultCity', help_text='District where project is present', max_length=100),
        ),
        migrations.AddField(
            model_name='projectshapefile',
            name='district',
            field=models.CharField(default='defaultCity', help_text='District where project is present', max_length=100),
        ),
        migrations.AddField(
            model_name='rainfalldataset',
            name='district',
            field=models.CharField(default='defaultCity', help_text='District where project is present', max_length=100),
        ),
        migrations.AddField(
            model_name='soilmoisturedataset',
            name='district',
            field=models.CharField(default='defaultCity', help_text='District where project is present', max_length=100),
        ),
        migrations.AddField(
            model_name='temperaturedata',
            name='district',
            field=models.CharField(default='defaultCity', help_text='District where project is present', max_length=100),
        ),
        migrations.AlterField(
            model_name='forestfirealert',
            name='district',
            field=models.CharField(default='defaultCity', help_text='District where forest fire was reported', max_length=100),
        ),
        migrations.AlterField(
            model_name='forestfiredata',
            name='district',
            field=models.CharField(default='defaultCity', help_text='District where forest fire was reported', max_length=100),
        ),
        migrations.AlterField(
            model_name='livestockdata',
            name='district',
            field=models.CharField(default='defaultCity', help_text='District where project is present', max_length=100),
        ),
    ]
